import transformer from './cycling-outputs';
import TEST_DATA from '../data/workouts.json';

describe('transform()', () => {
  test('Calculate average output trends over time', async () => {
    const transformed = transformer({ data: TEST_DATA });
    // console.log(transformed); // Useful while iterating, remove when results look correct
    // expect(true).toBe(true); // Useful while iterating, remove when results look correct
    expect(transformed).toMatchInlineSnapshot(`
      Object {
        "byRideLength": Object {
          "10": Object {
            "data": Array [
              Object {
                "instructor": "Leanne Hainsby",
                "title": "10 min Low Impact Ride",
                "x": "2019-04-14",
                "y": 119,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "10 min Low Impact Ride",
                "x": "2019-05-04",
                "y": 124,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "10 min Climb Ride",
                "x": "2019-07-07",
                "y": 131,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "10 min Low Impact Ride",
                "x": "2019-10-13",
                "y": 157,
              },
            ],
            "id": "10",
          },
          "15": Object {
            "data": Array [
              Object {
                "instructor": "Matt Wilpers",
                "title": "15 min Warm Up Ride",
                "x": "2019-02-19",
                "y": 100,
              },
              Object {
                "instructor": "",
                "title": "15 min 53 sec Just Ride",
                "x": "2019-03-11",
                "y": 141,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "15 min Hip Hop Ride",
                "x": "2019-05-31",
                "y": 186,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "15 min Low Impact Ride",
                "x": "2019-06-02",
                "y": 175,
              },
              Object {
                "instructor": "Ally Love",
                "title": "15 min Hip Hop Ride",
                "x": "2019-06-12",
                "y": 198,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "15 min Low Impact Ride",
                "x": "2019-06-17",
                "y": 180,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "15 min Pop Ride",
                "x": "2019-06-19",
                "y": 200,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min Climb Ride",
                "x": "2019-06-24",
                "y": 169,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "15 min 80s Ride",
                "x": "2019-07-05",
                "y": 210,
              },
              Object {
                "instructor": "Christine D'Ercole",
                "title": "15 min New Wave Ride",
                "x": "2019-07-13",
                "y": 204,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "15 min Low Impact Ride",
                "x": "2019-07-20",
                "y": 212,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "15 min 80s Ride",
                "x": "2019-08-02",
                "y": 214,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "15 min Tabata Ride",
                "x": "2019-08-05",
                "y": 215,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min Low Impact Ride",
                "x": "2019-08-15",
                "y": 217,
              },
              Object {
                "instructor": "Ally Love",
                "title": "15 min Tabata Ride",
                "x": "2019-09-03",
                "y": 218,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min Low Impact Ride",
                "x": "2019-09-06",
                "y": 220,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min HIIT Ride",
                "x": "2019-09-25",
                "y": 223,
              },
              Object {
                "instructor": "Ally Love",
                "title": "15 min Pop Ride",
                "x": "2019-09-26",
                "y": 230,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "15 min Pop Ride",
                "x": "2019-11-04",
                "y": 231,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "15 min Tabata Ride",
                "x": "2019-12-16",
                "y": 203,
              },
              Object {
                "instructor": "Hannah Frankson",
                "title": "15 min HIIT Ride",
                "x": "2019-12-18",
                "y": 213,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "15 min Hip Hop Ride",
                "x": "2019-12-31",
                "y": 232,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min HIIT Ride",
                "x": "2020-01-02",
                "y": 234,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min Low Impact Ride",
                "x": "2020-01-15",
                "y": 235,
              },
              Object {
                "instructor": "Sam Yo",
                "title": "15 min HIIT Ride",
                "x": "2020-01-20",
                "y": 220,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "15 min Tabata Ride",
                "x": "2020-02-17",
                "y": 236,
              },
            ],
            "id": "15",
          },
          "20": Object {
            "data": Array [
              Object {
                "instructor": "Ally Love",
                "title": "20 min Beginner Ride",
                "x": "2019-02-17",
                "y": 118,
              },
              Object {
                "instructor": "Cody Rigsby",
                "title": "20 min Beginner Ride",
                "x": "2019-02-20",
                "y": 127,
              },
              Object {
                "instructor": "Ally Love",
                "title": "20 min HIIT Ride",
                "x": "2019-03-31",
                "y": 212,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min Hip Hop Ride",
                "x": "2019-04-25",
                "y": 232,
              },
              Object {
                "instructor": "Jess King",
                "title": "20 min Hip Hop Ride",
                "x": "2019-04-29",
                "y": 244,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "20 min HIIT Ride",
                "x": "2019-05-02",
                "y": 220,
              },
              Object {
                "instructor": "Cody Rigsby",
                "title": "20 min Pop Ride",
                "x": "2019-05-13",
                "y": 236,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "20 min HIIT Ride",
                "x": "2019-05-20",
                "y": 235,
              },
              Object {
                "instructor": "Robin Arzon",
                "title": "20 min HIIT Ride",
                "x": "2019-05-22",
                "y": 247,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "20 min Hip Hop Ride",
                "x": "2019-05-26",
                "y": 242,
              },
              Object {
                "instructor": "Jennifer Jacobs",
                "title": "20 min 80s Pop Ride",
                "x": "2019-05-29",
                "y": 250,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "20 min Pop Ride",
                "x": "2019-06-03",
                "y": 247,
              },
              Object {
                "instructor": "Cody Rigsby",
                "title": "20 min HIIT Ride",
                "x": "2019-06-18",
                "y": 252,
              },
              Object {
                "instructor": "Robin Arzon",
                "title": "20 min Low Impact Ride",
                "x": "2019-06-26",
                "y": 260,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "20 min 90s Rock Ride",
                "x": "2019-06-27",
                "y": 264,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "20 min Hip Hop Ride",
                "x": "2019-07-03",
                "y": 235,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "20 min British Rock Ride",
                "x": "2019-07-17",
                "y": 268,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "20 min Low Impact Ride",
                "x": "2019-08-04",
                "y": 270,
              },
              Object {
                "instructor": "Ally Love",
                "title": "20 min Classic Rock Ride",
                "x": "2019-08-12",
                "y": 275,
              },
              Object {
                "instructor": "Jess King",
                "title": "20 min Trap Music Ride",
                "x": "2019-08-19",
                "y": 281,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "20 min Low Impact Ride",
                "x": "2019-08-20",
                "y": 282,
              },
              Object {
                "instructor": "Olivia Amato",
                "title": "20 min Pop Ride",
                "x": "2019-08-21",
                "y": 288,
              },
              Object {
                "instructor": "Cody Rigsby",
                "title": "20 min Pop Ride",
                "x": "2019-09-04",
                "y": 290,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min New Tracks Ride",
                "x": "2019-09-10",
                "y": 292,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min 80s Ride",
                "x": "2019-09-17",
                "y": 260,
              },
              Object {
                "instructor": "Ally Love",
                "title": "20 min HIIT Ride",
                "x": "2019-09-19",
                "y": 294,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "20 min UK Celebration Ride",
                "x": "2019-09-24",
                "y": 300,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "20 min UK Celebration Ride",
                "x": "2019-09-24",
                "y": 301,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min 80s Pop Ride",
                "x": "2019-10-07",
                "y": 302,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min Hip Hop Ride",
                "x": "2019-10-14",
                "y": 303,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min HIIT Ride",
                "x": "2019-10-15",
                "y": 304,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min Tabata Ride",
                "x": "2019-11-05",
                "y": 305,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "20 min Tabata Ride",
                "x": "2019-11-06",
                "y": 306,
              },
              Object {
                "instructor": "Ally Love",
                "title": "20 min Hip Hop Ride",
                "x": "2019-11-14",
                "y": 300,
              },
              Object {
                "instructor": "Jess King",
                "title": "20 min Trap Music Ride",
                "x": "2020-01-22",
                "y": 301,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "20 min 80s Ride",
                "x": "2020-01-24",
                "y": 303,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "20 min HIIT Ride",
                "x": "2020-01-29",
                "y": 289,
              },
              Object {
                "instructor": "Matt Wilpers",
                "title": "20 min FTP Test Ride",
                "x": "2020-01-31",
                "y": 307,
              },
              Object {
                "instructor": "Sam Yo",
                "title": "20 min Recovery Ride",
                "x": "2020-02-04",
                "y": 288,
              },
              Object {
                "instructor": "Hannah Frankson",
                "title": "20 min Hip Hop Ride",
                "x": "2020-02-13",
                "y": 300,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "20 min 80s Ride",
                "x": "2020-03-10",
                "y": 279,
              },
              Object {
                "instructor": "Sam Yo",
                "title": "20 min 80s Ride",
                "x": "2020-03-18",
                "y": 275,
              },
            ],
            "id": "20",
          },
          "30": Object {
            "data": Array [
              Object {
                "instructor": "Denis Morton",
                "title": "30 min Low Impact Ride",
                "x": "2019-02-22",
                "y": 163,
              },
              Object {
                "instructor": "",
                "title": "30 min Maine Scenic Ride",
                "x": "2019-02-25",
                "y": 1,
              },
              Object {
                "instructor": "Jennifer Jacobs",
                "title": "30 min 80s Pop Ride",
                "x": "2019-02-28",
                "y": 252,
              },
              Object {
                "instructor": "Jenn Sherman",
                "title": "30 min Low Impact Ride",
                "x": "2019-03-01",
                "y": 219,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "30 min Pop Ride",
                "x": "2019-03-07",
                "y": 271,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "30 min Advanced Beginner Ride",
                "x": "2019-03-13",
                "y": 2,
              },
              Object {
                "instructor": "Leanne Hainsby",
                "title": "30 min British Pop Ride",
                "x": "2019-03-20",
                "y": 326,
              },
              Object {
                "instructor": "Ally Love",
                "title": "30 min Pop Ride",
                "x": "2019-03-25",
                "y": 331,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min HIIT Ride",
                "x": "2019-03-27",
                "y": 302,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min HIIT Ride",
                "x": "2019-04-23",
                "y": 333,
              },
              Object {
                "instructor": "",
                "title": "30 min 1 sec Just Ride",
                "x": "2019-04-27",
                "y": 324,
              },
              Object {
                "instructor": "Denis Morton",
                "title": "30 min HIIT Ride",
                "x": "2019-05-06",
                "y": 290,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "30 min Advanced Beginner Ride",
                "x": "2019-05-10",
                "y": 334,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Hip Hop Ride",
                "x": "2019-05-11",
                "y": 344,
              },
              Object {
                "instructor": "Jennifer Jacobs",
                "title": "30 min 80s Rock Ride",
                "x": "2019-05-16",
                "y": 328,
              },
              Object {
                "instructor": "Olivia Amato",
                "title": "30 min Pop Ride",
                "x": "2019-05-24",
                "y": 350,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "30 min House Ride",
                "x": "2019-06-05",
                "y": 356,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Hip Hop Ride",
                "x": "2019-06-07",
                "y": 362,
              },
              Object {
                "instructor": "Olivia Amato",
                "title": "30 min EDM/Electronic Dance Ride",
                "x": "2019-06-08",
                "y": 367,
              },
              Object {
                "instructor": "Olivia Amato",
                "title": "30 min Hip Hop Ride",
                "x": "2019-06-13",
                "y": 356,
              },
              Object {
                "instructor": "",
                "title": "30 min 59 sec Just Ride",
                "x": "2019-06-16",
                "y": 340,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min HIIT Ride",
                "x": "2019-06-20",
                "y": 369,
              },
              Object {
                "instructor": "",
                "title": "30 min 27 sec Just Ride",
                "x": "2019-07-04",
                "y": 343,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Club Bangers Ride",
                "x": "2019-07-10",
                "y": 378,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "30 min 80s Ride",
                "x": "2019-07-15",
                "y": 403,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Tabata Ride",
                "x": "2019-07-18",
                "y": 405,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Rock Ride",
                "x": "2019-07-28",
                "y": 410,
              },
              Object {
                "instructor": "Olivia Amato",
                "title": "30 min Hip Hop Ride",
                "x": "2019-07-31",
                "y": 396,
              },
              Object {
                "instructor": "Ally Love",
                "title": "30 min Pop Ride",
                "x": "2019-08-01",
                "y": 421,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min Classic Rock Ride",
                "x": "2019-08-07",
                "y": 425,
              },
              Object {
                "instructor": "Ally Love",
                "title": "30 min New Tracks Ride",
                "x": "2019-08-16",
                "y": 427,
              },
              Object {
                "instructor": "Ally Love",
                "title": "30 min Pop Ride",
                "x": "2019-08-22",
                "y": 430,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "30 min Low Impact Ride",
                "x": "2019-08-29",
                "y": 400,
              },
              Object {
                "instructor": "Hannah Marie Corbin",
                "title": "30 min Pick-Me-Up Ride",
                "x": "2019-08-30",
                "y": 413,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Hip Hop Ride",
                "x": "2019-09-01",
                "y": 432,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min 80s Rock Ride",
                "x": "2019-09-13",
                "y": 436,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min 80s Ride",
                "x": "2019-09-18",
                "y": 439,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min Rock Ride",
                "x": "2019-09-27",
                "y": 445,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min 80s Ride",
                "x": "2019-11-07",
                "y": 446,
              },
              Object {
                "instructor": "Tunde Oyeneyin",
                "title": "30 min Live DJ Ride",
                "x": "2019-11-15",
                "y": 400,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "30 min Low Impact Ride",
                "x": "2019-12-19",
                "y": 410,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "30 min 80s Ride",
                "x": "2019-12-21",
                "y": 359,
              },
              Object {
                "instructor": "Ally Love",
                "title": "30 min Holiday Ride",
                "x": "2019-12-24",
                "y": 421,
              },
              Object {
                "instructor": "Kendall Toole",
                "title": "30 min Holiday Ride",
                "x": "2019-12-25",
                "y": 423,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Intervals & Arms Ride",
                "x": "2020-01-07",
                "y": 412,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Pop Ride",
                "x": "2020-02-06",
                "y": 411,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min HIIT Ride",
                "x": "2020-02-11",
                "y": 447,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Hip Hop Ride",
                "x": "2020-02-19",
                "y": 427,
              },
              Object {
                "instructor": "Matt Wilpers",
                "title": "30 min Power Zone Endurance Ride",
                "x": "2020-02-21",
                "y": 419,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Hip Hop Ride",
                "x": "2020-02-24",
                "y": 436,
              },
              Object {
                "instructor": "Ally Love",
                "title": "30 min Pop Ride",
                "x": "2020-03-12",
                "y": 421,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "30 min 80s Ride",
                "x": "2020-03-16",
                "y": 428,
              },
              Object {
                "instructor": "Jess King",
                "title": "30 min EDM/Electronic Dance Ride",
                "x": "2020-03-20",
                "y": 432,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min HIIT Ride",
                "x": "2020-03-24",
                "y": 434,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "30 min 80s Rock Ride",
                "x": "2020-03-26",
                "y": 433,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Hip Hop Ride",
                "x": "2020-03-30",
                "y": 432,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min Intervals & Arms Ride",
                "x": "2020-04-01",
                "y": 437,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "30 min HIIT & Hills Ride",
                "x": "2020-04-03",
                "y": 433,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "30 min New Tracks Ride",
                "x": "2020-04-07",
                "y": 426,
              },
              Object {
                "instructor": "Kendall Toole",
                "title": "30 min Metal Ride",
                "x": "2020-04-09",
                "y": 440,
              },
              Object {
                "instructor": "Tunde Oyeneyin",
                "title": "30 min Hip Hop Ride",
                "x": "2020-04-13",
                "y": 437,
              },
            ],
            "id": "30",
          },
          "45": Object {
            "data": Array [
              Object {
                "instructor": "Cody Rigsby",
                "title": "45 min 90s Pop Ride",
                "x": "2019-02-14",
                "y": 84,
              },
              Object {
                "instructor": "Jenn Sherman",
                "title": "45 min Y2K Ride",
                "x": "2019-03-11",
                "y": 0,
              },
              Object {
                "instructor": "",
                "title": "45 min 15 sec Just Ride",
                "x": "2019-03-16",
                "y": 353,
              },
              Object {
                "instructor": "Jenn Sherman",
                "title": "45 min 80s Pop Ride",
                "x": "2019-03-28",
                "y": 461,
              },
              Object {
                "instructor": "Jennifer Jacobs",
                "title": "45 min 80s Ride",
                "x": "2019-03-29",
                "y": 451,
              },
              Object {
                "instructor": "",
                "title": "45 min 4 sec Just Ride",
                "x": "2019-04-01",
                "y": 417,
              },
              Object {
                "instructor": "Robin Arzon",
                "title": "45 min Hip Hop Ride",
                "x": "2019-04-19",
                "y": 475,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min Electronic Dance/EDM Ride",
                "x": "2019-04-24",
                "y": 0,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min Live DJ Ride",
                "x": "2019-05-05",
                "y": 479,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Club Bangers Ride",
                "x": "2019-05-11",
                "y": 1,
              },
              Object {
                "instructor": "Robin Arzon",
                "title": "45 min Live DJ Ride",
                "x": "2019-05-15",
                "y": 482,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min 80s Ride",
                "x": "2019-05-30",
                "y": 501,
              },
              Object {
                "instructor": "Ally Love",
                "title": "45 min New Tracks Ride",
                "x": "2019-06-14",
                "y": 511,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min 80s Ride",
                "x": "2019-06-15",
                "y": 489,
              },
              Object {
                "instructor": "Denis Morton",
                "title": "45  min 80s Ride",
                "x": "2019-07-01",
                "y": 518,
              },
              Object {
                "instructor": "Robin Arzon",
                "title": "45 min Tabata Ride",
                "x": "2019-07-02",
                "y": 528,
              },
              Object {
                "instructor": "Cycling Instructors 2019",
                "title": "45 min All for One Ride",
                "x": "2019-07-08",
                "y": 557,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Pop Ride",
                "x": "2019-07-19",
                "y": 570,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min EDM/Electronic Dance Ride",
                "x": "2019-07-22",
                "y": 593,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Intervals & Arms Ride",
                "x": "2019-07-27",
                "y": 600,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Intervals & Arms Ride",
                "x": "2019-08-08",
                "y": 602,
              },
              Object {
                "instructor": "Christine D'Ercole",
                "title": "45 min 90s Rock Ride",
                "x": "2019-08-14",
                "y": 261,
              },
              Object {
                "instructor": "Olivia Amato",
                "title": "45 min Intervals & Arms Ride",
                "x": "2019-08-17",
                "y": 605,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min Groove Ride",
                "x": "2019-08-28",
                "y": 611,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Intervals & Arms Ride",
                "x": "2019-09-02",
                "y": 620,
              },
              Object {
                "instructor": "Christine D'Ercole",
                "title": "45 min HRZ Max Capacity Ride",
                "x": "2019-09-09",
                "y": 623,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min 90s Pop Ride",
                "x": "2019-09-11",
                "y": 626,
              },
              Object {
                "instructor": "Jess King",
                "title": "45 min Live DJ Ride",
                "x": "2019-09-20",
                "y": 635,
              },
              Object {
                "instructor": "",
                "title": "45 min 25 sec Just Ride",
                "x": "2019-09-29",
                "y": 584,
              },
              Object {
                "instructor": "Emma Lovewell",
                "title": "45 min Climb Ride",
                "x": "2019-10-02",
                "y": 639,
              },
              Object {
                "instructor": "",
                "title": "45 min 27 sec Just Ride",
                "x": "2019-10-03",
                "y": 451,
              },
              Object {
                "instructor": "Matt Wilpers",
                "title": "45 min Live DJ Ride",
                "x": "2019-10-04",
                "y": 644,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Hip Hop Ride",
                "x": "2019-10-18",
                "y": 650,
              },
              Object {
                "instructor": "Kendall Toole",
                "title": "45 min Hip Hop Ride",
                "x": "2019-12-14",
                "y": 500,
              },
              Object {
                "instructor": "Hannah Frankson",
                "title": "45 min Hip Hop Ride",
                "x": "2019-12-15",
                "y": 565,
              },
              Object {
                "instructor": "Ben Alldis",
                "title": "45 min Boxing Day Burn Ride",
                "x": "2019-12-26",
                "y": 592,
              },
              Object {
                "instructor": "Christine D'Ercole",
                "title": "45 min HRZ Endurance Ride",
                "x": "2019-12-30",
                "y": 571,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Club Bangers Ride",
                "x": "2020-02-22",
                "y": 633,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Pop Ride",
                "x": "2020-03-22",
                "y": 645,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Club Bangers Ride",
                "x": "2020-03-28",
                "y": 651,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Intervals & Arms Ride",
                "x": "2020-04-05",
                "y": 656,
              },
              Object {
                "instructor": "Alex Toussaint",
                "title": "45 min Hip Hop Ride",
                "x": "2020-04-11",
                "y": 639,
              },
            ],
            "id": "45",
          },
          "5": Object {
            "data": Array [
              Object {
                "instructor": "Hannah Frankson",
                "title": "5 min Cool Down Ride",
                "x": "2019-11-15",
                "y": 37,
              },
            ],
            "id": "5",
          },
          "60": Object {
            "data": Array [
              Object {
                "instructor": "Alex Toussaint",
                "title": "60 min Hip Hop Ride",
                "x": "2019-06-11",
                "y": 666,
              },
              Object {
                "instructor": "Matt Wilpers",
                "title": "60 min Power Zone Ride",
                "x": "2019-07-12",
                "y": 706,
              },
              Object {
                "instructor": "Matt Wilpers",
                "title": "60 min Power Zone Ride",
                "x": "2019-08-10",
                "y": 804,
              },
            ],
            "id": "60",
          },
        },
      }
    `); // Enable this once transformer is working as expected to protect against regression
  });
});
