import transformer from "./total-workouts";

const data = mockData();

// TODO: more Jest config later?
// https://developer-log.netlify.app/testing-react-components-with-jest-enzyme-nextjs/
// https://jestjs.io/docs/en/getting-started
describe("transform()", () => {
  test("Convert raw data to calculated totals", async () => {
    const totals = transformer({ data });
    expect(totals).toMatchInlineSnapshot(`
      Object {
        "caloriesBurned": 1336,
        "distanceInMiles": 45,
        "numberOfWorkouts": 13,
        "numberOfWorkoutsByDiscipline": Object {
          "Cycling": 8,
          "Stretching": 5,
        },
        "numberOfWorkoutsByDisciplinePieData": Array [
          Object {
            "id": "Cycling",
            "value": 8,
          },
          Object {
            "id": "Stretching",
            "value": 5,
          },
        ],
        "timeInMinutes": 264,
      }
    `);
  });
});

function mockData() {
  return [
    {
      "Workout Timestamp": "2019-02-14 18:34 (EDT)",
      "Live/On-Demand": "Live",
      "Instructor Name": "Cody Rigsby",
      "Length (minutes)": 45,
      "Fitness Discipline": "Cycling",
      Type: "Theme",
      Title: "45 min 90s Pop Ride",
      "Class Timestamp": "2019-02-14 18:22 (EDT)",
      "Total Output": 84,
      "Avg. Watts": 113,
      "Avg. Resistance": "38%",
      "Avg. Cadence (RPM)": 79,
      "Avg. Speed (mph)": 16.11,
      "Distance (mi)": 3.34,
      "Calories Burned": 111,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-14 19:11 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Leanne Hainsby",
      "Length (minutes)": 5,
      "Fitness Discipline": "Stretching",
      Type: "Pre & Post-Ride Stretch",
      Title: "5 min Post-Ride Stretch",
      "Class Timestamp": "2019-02-13 00:14 (EDT)",
      "Total Output": "",
      "Avg. Watts": "",
      "Avg. Resistance": "",
      "Avg. Cadence (RPM)": "",
      "Avg. Speed (mph)": "",
      "Distance (mi)": "",
      "Calories Burned": 5,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-17 16:15 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Ally Love",
      "Length (minutes)": 20,
      "Fitness Discipline": "Cycling",
      Type: "Beginner",
      Title: "20 min Beginner Ride",
      "Class Timestamp": "2018-08-16 14:00 (EDT)",
      "Total Output": 118,
      "Avg. Watts": 99,
      "Avg. Resistance": "36%",
      "Avg. Cadence (RPM)": 85,
      "Avg. Speed (mph)": 15.75,
      "Distance (mi)": 5.25,
      "Calories Burned": 155,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-17 16:38 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Leanne Hainsby",
      "Length (minutes)": 5,
      "Fitness Discipline": "Stretching",
      Type: "Pre & Post-Ride Stretch",
      Title: "5 min Post-Ride Stretch",
      "Class Timestamp": "2019-02-13 00:14 (EDT)",
      "Total Output": "",
      "Avg. Watts": "",
      "Avg. Resistance": "",
      "Avg. Cadence (RPM)": "",
      "Avg. Speed (mph)": "",
      "Distance (mi)": "",
      "Calories Burned": 28,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-19 18:51 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Matt Wilpers",
      "Length (minutes)": 15,
      "Fitness Discipline": "Cycling",
      Type: "Low Impact",
      Title: "15 min Warm Up Ride",
      "Class Timestamp": "2018-07-30 14:35 (EDT)",
      "Total Output": 100,
      "Avg. Watts": 111,
      "Avg. Resistance": "37%",
      "Avg. Cadence (RPM)": 89,
      "Avg. Speed (mph)": 16.47,
      "Distance (mi)": 4.12,
      "Calories Burned": 132,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-19 19:07 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Matt Wilpers",
      "Length (minutes)": 5,
      "Fitness Discipline": "Stretching",
      Type: "Pre & Post-Ride Stretch",
      Title: "5 min Post-Ride Stretch",
      "Class Timestamp": "2019-01-03 15:11 (EDT)",
      "Total Output": "",
      "Avg. Watts": "",
      "Avg. Resistance": "",
      "Avg. Cadence (RPM)": "",
      "Avg. Speed (mph)": "",
      "Distance (mi)": "",
      "Calories Burned": 14,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-20 18:16 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Cody Rigsby",
      "Length (minutes)": 20,
      "Fitness Discipline": "Cycling",
      Type: "Theme",
      Title: "20 min Beginner Ride",
      "Class Timestamp": "2018-08-24 15:11 (EDT)",
      "Total Output": 127,
      "Avg. Watts": 106,
      "Avg. Resistance": "35%",
      "Avg. Cadence (RPM)": 90,
      "Avg. Speed (mph)": 15.96,
      "Distance (mi)": 5.31,
      "Calories Burned": 167,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-20 18:39 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Cody Rigsby",
      "Length (minutes)": 5,
      "Fitness Discipline": "Stretching",
      Type: "Pre & Post-Ride Stretch",
      Title: "5 min Post-Ride Stretch",
      "Class Timestamp": "2019-02-07 15:10 (EDT)",
      "Total Output": "",
      "Avg. Watts": "",
      "Avg. Resistance": "",
      "Avg. Cadence (RPM)": "",
      "Avg. Speed (mph)": "",
      "Distance (mi)": "",
      "Calories Burned": 11,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-22 18:32 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Denis Morton",
      "Length (minutes)": 30,
      "Fitness Discipline": "Cycling",
      Type: "Low Impact",
      Title: "30 min Low Impact Ride",
      "Class Timestamp": "2018-08-04 15:18 (EDT)",
      "Total Output": 163,
      "Avg. Watts": 91,
      "Avg. Resistance": "34%",
      "Avg. Cadence (RPM)": 86,
      "Avg. Speed (mph)": 14.87,
      "Distance (mi)": 7.42,
      "Calories Burned": 214,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-22 19:05 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "Denis Morton",
      "Length (minutes)": 5,
      "Fitness Discipline": "Stretching",
      Type: "Pre & Post-Ride Stretch",
      Title: "5 min Post-Ride Stretch",
      "Class Timestamp": "2019-02-15 14:26 (EDT)",
      "Total Output": "",
      "Avg. Watts": "",
      "Avg. Resistance": "",
      "Avg. Cadence (RPM)": "",
      "Avg. Speed (mph)": "",
      "Distance (mi)": "",
      "Calories Burned": 14,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-23 10:04 (EDT)",
      "Live/On-Demand": "",
      "Instructor Name": "",
      "Length (minutes)": 44,
      "Fitness Discipline": "Cycling",
      Type: "",
      Title: "44 min 31 sec Just Ride",
      "Class Timestamp": "",
      "Total Output": 181,
      "Avg. Watts": 68,
      "Avg. Resistance": "27%",
      "Avg. Cadence (RPM)": 100,
      "Avg. Speed (mph)": 13.61,
      "Distance (mi)": 10.09,
      "Calories Burned": 239,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-24 09:21 (EDT)",
      "Live/On-Demand": "",
      "Instructor Name": "",
      "Length (minutes)": 35,
      "Fitness Discipline": "Cycling",
      Type: "",
      Title: "35 min 41 sec Just Ride",
      "Class Timestamp": "",
      "Total Output": 186,
      "Avg. Watts": 87,
      "Avg. Resistance": "28%",
      "Avg. Cadence (RPM)": 111,
      "Avg. Speed (mph)": 15.21,
      "Distance (mi)": 9.05,
      "Calories Burned": 245,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    },
    {
      "Workout Timestamp": "2019-02-25 21:11 (EDT)",
      "Live/On-Demand": "On Demand",
      "Instructor Name": "",
      "Length (minutes)": 30,
      "Fitness Discipline": "Cycling",
      Type: "Scenic Ride",
      Title: "30 min Maine Scenic Ride",
      "Class Timestamp": "",
      "Total Output": 1,
      "Avg. Watts": 30,
      "Avg. Resistance": "28%",
      "Avg. Cadence (RPM)": 47,
      "Avg. Speed (mph)": 7.18,
      "Distance (mi)": 0.06,
      "Calories Burned": 1,
      "Avg. Heartrate": "",
      "Avg. Incline": "",
      "Avg. Pace (min/mi)": ""
    }
  ];
}
